# Generated by Django 2.2.6 on 2020-01-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatRobotLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('open_id', models.CharField(blank=True, max_length=32, null=True)),
                ('user_text', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wechat_robot_log',
                'managed': False,
            },
        ),
    ]
